upload post api accessed at2023-05-01 06:36:46.019712 hours! - <QueryDict: {'description': ['wdemckwme'], 'post': [<InMemoryUploadedFile: 625599@2x.png (image/png)>]}>
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
Unsupported Media Type: /api/user/posts/upload/
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /api/user/posts/upload/
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
upload post api accessed at 2023-05-01 07:18:31.960277 hours!  - <QueryDict: {'description': ['wdemckwme'], 'post': [<InMemoryUploadedFile: 625599@2x.png (image/png)>]}>
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
upload post api accessed at 2023-05-01 10:47:38.228046 hours!  - <QueryDict: {'description': ['wdemckwme'], 'post': [<InMemoryUploadedFile: 625599@2x.png (image/png)>]}>
Internal Server Error: /api/user/posts/upload/
Traceback (most recent call last):
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/template/response.py", line 111, in render
    self.content = self.rendered_content
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/utils/encoders.py", line 50, in default
    return obj.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
upload post api accessed at 2023-05-01 11:08:41.197484 hours!  - <QueryDict: {'description': ['wdemckwme'], 'post': [<InMemoryUploadedFile: 625599@2x.png (image/png)>]}>
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
upload post api accessed at 2023-05-01 11:42:05.343397 hours!  - <QueryDict: {'description': ['wdemckwme'], 'post': [<InMemoryUploadedFile: 625599@2x.png (image/png)>]}>
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_post.py changed, reloading.
Watching for file changes with StatReloader
upload post api accessed at 2023-05-01 11:43:32.632374 hours!  - <QueryDict: {'description': ['wdemckwme'], 'post': [<InMemoryUploadedFile: 625599@2x.png (image/png)>]}>
Not Found: /favicon.ico
/home/aashish/Desktop/talvido-app/talvido/talvido_app/models.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/reels/views/add/
Traceback (most recent call last):
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_reels.py", line 119, in post
    reel_view_serializer.save()
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py", line 51, in create
    reel = reel_view.save()
AttributeError: 'int' object has no attribute 'save'
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/reels/views/add/
Traceback (most recent call last):
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_reels.py", line 119, in post
    reel_view_serializer.save()
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py", line 51, in create
    reel = reel.save()
AttributeError: 'int' object has no attribute 'save'
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/reels/views/add/
Traceback (most recent call last):
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_reels.py", line 119, in post
    reel_view_serializer.save()
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 213, in save
    assert self.instance is not None, (
AssertionError: `create()` did not return an object instance.
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/reels/views/add/
Traceback (most recent call last):
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_reels.py", line 119, in post
    reel_view_serializer.save()
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 213, in save
    assert self.instance is not None, (
AssertionError: `create()` did not return an object instance.
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
Bad Request: /api/reels/views/add/
Bad Request: /api/reels/views/add/
Unauthorized: /api/user/reels/active/
Unauthorized: /api/user/reels/active/
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/user/reels/active/
Traceback (most recent call last):
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_reels.py", line 30, in get
    "data": reels_serializer.data,
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
AssertionError: The field 'reel_views' was declared on serializer GetReelModelSerializer, but has not been included in the 'fields' option.
Internal Server Error: /api/user/reels/active/
Traceback (most recent call last):
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_reels.py", line 30, in get
    "data": reels_serializer.data,
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 1148, in get_field_names
    assert field_name in fields, (
AssertionError: The field 'reel_views' was declared on serializer GetReelModelSerializer, but has not been included in the 'fields' option.
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/user/reels/active/
Traceback (most recent call last):
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_reels.py", line 30, in get
    "data": reels_serializer.data,
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py", line 26, in get_reel_views
    reel_view = Reel.objects.get(data.reel.id).reel_view_reel.views
AttributeError: 'FieldFile' object has no attribute 'id'
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/user/reels/active/
Traceback (most recent call last):
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_reels.py", line 30, in get
    "data": reels_serializer.data,
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py", line 26, in get_reel_views
    reel_view = Reel.objects.get(data.reel).reel_view_reel.views
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 623, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1498, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1529, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1376, in build_filter
    arg, value = filter_expr
ValueError: too many values to unpack (expected 2)
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/user/reels/active/
Traceback (most recent call last):
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_reels.py", line 30, in get
    "data": reels_serializer.data,
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py", line 26, in get_reel_views
    reel_view = Reel.objects.get(data.id).reel_view_reel.views
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 623, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1498, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1529, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1376, in build_filter
    arg, value = filter_expr
TypeError: cannot unpack non-iterable int object
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/user/reels/active/
Traceback (most recent call last):
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_reels.py", line 30, in get
    "data": reels_serializer.data,
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py", line 26, in get_reel_views
    reel_view = Reel.objects.get(data.id).reel_view_reel.views
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 623, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1498, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1529, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1376, in build_filter
    arg, value = filter_expr
TypeError: cannot unpack non-iterable int object
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/user/reels/active/
Traceback (most recent call last):
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_reels.py", line 30, in get
    "data": reels_serializer.data,
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py", line 26, in get_reel_views
    reel_view = Reel.objects.get(data.id).reel_view_reel.views
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 623, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1498, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1529, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1376, in build_filter
    arg, value = filter_expr
TypeError: cannot unpack non-iterable int object
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/user/reels/active/
Traceback (most recent call last):
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_reels.py", line 30, in get
    "data": reels_serializer.data,
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py", line 26, in get_reel_views
    reel = Reel.objects.get(data.id)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 623, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1498, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1529, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1376, in build_filter
    arg, value = filter_expr
TypeError: cannot unpack non-iterable int object
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/user/reels/active/
Traceback (most recent call last):
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/api_reels.py", line 30, in get
    "data": reels_serializer.data,
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/rest_framework/fields.py", line 1838, in to_representation
    return method(value)
  File "/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py", line 26, in get_reel_views
    reel = Reel.objects.get(data.id)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 623, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1498, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1529, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/aashish/Desktop/talvido-app/env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1376, in build_filter
    arg, value = filter_expr
TypeError: cannot unpack non-iterable int object
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
/home/aashish/Desktop/talvido-app/talvido/talvido_app/api/serializers/reels_serializer.py changed, reloading.
Watching for file changes with StatReloader
